import '../css/styles.css';
import './header';
import './footer';
import './tag/allMaterials';
import './tag/pagination';
import './tag/importantNews';
import './relatedNews';
import './main/importantNews';
import './main/editorsChoice';
import './main/columns';
import './main/blog';
import './socials';
import './main/lastNews';
import './main/exchangeForecasts';
import './themeTags';
import './category/mostInteresting';
import './category/allMaterialsCategory';
import './category/columnsCategory';

console.log('Webpack and Tailwind are working!');
